### ISSUE TITLE
common里的东西是如何自动生成的

### ISSUE THREAD

**Issue by Ultraman95** [calebx/ctp-alone#1]

**Comment by calebx** [comment]
@Ultraman95 绝大部分内容是通过 [rust-bindgen](https://github.com/rust-lang/rust-bindgen) 跑出来的。

cargo script > run generate.rs -> rust-bindgen -> Done

**Comment by Ultraman95** [comment]
你的工程可以通过cargo build编译出可运行的程序吗？

**Comment by Ultraman95** [comment]
最好能把行情跑起来呢，我们也能玩一玩

**Comment by calebx** [comment]
可以啊。
需要simnow.com.cn 注册一个模拟帐号，可能需要强制修改一下密码；
然后就可以run example了。
不过他们的服务器是不稳定的，只能在有效的开市时间里面运行。

setup env as:
```
 export CTP_MD_URL="tcp://180.168.146.187:10110"
 export CTP_TRADE_URL="tcp://180.168.146.187:10100"
 export CTP_BROKER_ID="9999"
 export CTP_USER_ID="xxx"
 export CTP_PASSWORD="xxx"
```

run cargo test as:
```
cargo run --example api
```
